// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-periodic-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function textResult(data) {
  return { content: [{ type: "text", text: JSON.stringify(data) }] };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
var APP_URL = "https://evita-hse-br.lovable.app";
function deepLink(path) {
  return `${APP_URL}${path}`;
}
async function planGate(ctx) {
  if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
  const { data, error } = await supabaseForUser(ctx).rpc("get_company_access_status");
  const obj = data;
  if (error || !obj || obj.error) return errorResult("Could not verify the company plan.");
  if (obj.status === "expired") return errorResult("The company plan is expired. Renew it to use the API.");
  if (obj.plan !== "enterprise" && obj.status !== "trial") {
    return errorResult("Agent/API (MCP) access is available on the Enterprise plan only.");
  }
  return null;
}

// src/lib/mcp/tools/list-periodic-services.ts
function statusOf(nextDueAt, alertDaysBefore) {
  if (!nextDueAt) return "unknown";
  const today = /* @__PURE__ */ new Date();
  today.setHours(0, 0, 0, 0);
  const diff = Math.floor(((/* @__PURE__ */ new Date(nextDueAt + "T00:00:00")).getTime() - today.getTime()) / 864e5);
  if (diff < 0) return "expired";
  if (diff <= (alertDaysBefore ?? 30)) return "warning";
  return "ok";
}
var list_periodic_services_default = defineTool({
  name: "list_periodic_services",
  title: "List periodic services",
  description: "List HSE periodic services for the signed-in user's company (name, category, last done, next due date and compliance status).",
  inputSchema: {
    status: z.enum(["ok", "warning", "expired", "all"]).optional().describe("Filter by compliance status."),
    limit: z.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    const denied = await planGate(ctx);
    if (denied) return denied;
    const { data, error } = await supabaseForUser(ctx).from("periodic_services").select("id,name,last_done_at,next_due_at,alert_days_before,supplier,status,service_categories(name)").eq("status", "active").order("next_due_at", { ascending: true }).limit(200);
    if (error) return errorResult(error.message);
    let rows = (data ?? []).map((r) => ({
      ...r,
      compliance_status: statusOf(r.next_due_at, r.alert_days_before),
      url: deepLink("/servicos")
    }));
    if (status && status !== "all") rows = rows.filter((r) => r.compliance_status === status);
    return textResult(rows.slice(0, limit));
  }
});

// src/lib/mcp/tools/list-occurrences.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_occurrences_default = defineTool2({
  name: "list_occurrences",
  title: "List incidents (IC & NC)",
  description: "List incidents, near misses, non-conformities and safety observations for the signed-in user's company.",
  inputSchema: {
    type: z2.enum(["incident", "near_miss", "non_conformity", "safety_observation"]).optional().describe("Filter by occurrence type."),
    open_only: z2.boolean().default(false).describe("Only occurrences that are not closed."),
    limit: z2.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, open_only, limit }, ctx) => {
    const denied = await planGate(ctx);
    if (denied) return denied;
    let query = supabaseForUser(ctx).from("occurrences").select(
      "id,description,type,severity,status,occurred_at,lost_days,with_leave,location,cat_required,cat_number,investigation_method"
    ).order("occurred_at", { ascending: false }).limit(limit);
    if (type) query = query.eq("type", type);
    if (open_only) query = query.neq("status", "closed");
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult((data ?? []).map((r) => ({ ...r, url: deepLink("/incidentes") })));
  }
});

// src/lib/mcp/tools/list-environmental-licenses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_environmental_licenses_default = defineTool3({
  name: "list_environmental_licenses",
  title: "List environmental licenses",
  description: "List environmental licenses (valid, expiring, expired or permanent) for the signed-in user's company.",
  inputSchema: { limit: z3.number().int().min(1).max(200).default(50) },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const denied = await planGate(ctx);
    if (denied) return denied;
    const { data, error } = await supabaseForUser(ctx).from("environmental_licenses").select("id,license_number,title,issuing_body,sphere,issued_at,expires_at,has_expiry,status,alert_days_before").order("expires_at", { ascending: true, nullsFirst: false }).limit(limit);
    if (error) return errorResult(error.message);
    return textResult((data ?? []).map((r) => ({ ...r, url: deepLink("/licencas") })));
  }
});

// src/lib/mcp/tools/list-suppliers.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_suppliers_default = defineTool4({
  name: "list_suppliers",
  title: "List suppliers",
  description: "List suppliers registered by the signed-in user's company.",
  inputSchema: {
    search: z4.string().optional().describe("Substring match on supplier name."),
    limit: z4.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    const denied = await planGate(ctx);
    if (denied) return denied;
    let q = supabaseForUser(ctx).from("suppliers_safe").select("*").order("name", { ascending: true }).limit(limit);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult(data);
  }
});

// src/lib/mcp/tools/list-epi-deliveries.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_epi_deliveries_default = defineTool5({
  name: "list_epi_deliveries",
  title: "List EPI deliveries",
  description: "List recent PPE (EPI) deliveries with employee, item and quantity.",
  inputSchema: { limit: z5.number().int().min(1).max(200).default(50) },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const denied = await planGate(ctx);
    if (denied) return denied;
    const { data, error } = await supabaseForUser(ctx).from("epi_deliveries").select("id,delivered_at,quantity,reason,employees(name),epi_types(name,unit)").order("delivered_at", { ascending: false }).limit(limit);
    if (error) return errorResult(error.message);
    return textResult(data);
  }
});

// src/lib/mcp/tools/get-dashboard-summary.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_dashboard_summary_default = defineTool6({
  name: "get_dashboard_summary",
  title: "HSE dashboard summary",
  description: "Summary counts for the signed-in user's company: open incidents, services and licenses needing attention, overdue CDFs, open corrective actions, deadlines in the next 30 days and total suppliers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const denied = await planGate(ctx);
    if (denied) return denied;
    const sb = supabaseForUser(ctx);
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const in30 = new Date(Date.now() + 30 * 864e5).toISOString().slice(0, 10);
    const soon = new Date(Date.now() + 30 * 864e5).toISOString().slice(0, 10);
    const [occ, srv, lic, sup, cdf, act, due] = await Promise.all([
      sb.from("occurrences").select("id", { count: "exact", head: true }).neq("status", "closed"),
      sb.from("periodic_services").select("id", { count: "exact", head: true }).eq("status", "active").lte("next_due_at", soon),
      sb.from("environmental_licenses").select("id", { count: "exact", head: true }).eq("has_expiry", true).lte("expires_at", in30),
      sb.from("suppliers_safe").select("id", { count: "exact", head: true }),
      sb.from("mtrs").select("id", { count: "exact", head: true }).neq("cdf_status", "received").lt("cdf_deadline_at", today),
      sb.from("corrective_actions").select("id", { count: "exact", head: true }).neq("status", "completed"),
      sb.from("calendar_due_items").select("source_id", { count: "exact", head: true }).lte("due_date", in30)
    ]);
    const err = [occ, srv, lic, sup, cdf, act, due].find((r) => r.error)?.error;
    if (err) return errorResult(err.message);
    return textResult({
      open_incidents: occ.count ?? 0,
      services_needing_attention: srv.count ?? 0,
      licenses_expiring_30d: lic.count ?? 0,
      overdue_cdf: cdf.count ?? 0,
      open_corrective_actions: act.count ?? 0,
      deadlines_next_30d: due.count ?? 0,
      suppliers_total: sup.count ?? 0
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "jspyzzrmonxvgicqakzv";
var mcp_default = defineMcp({
  name: "evita-hse-mcp",
  title: "Evita HSE",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in user's HSE data in Evita: periodic services, incidents (IC & NC), environmental licenses, suppliers, EPI deliveries, and a dashboard summary. All results are scoped to the user's company via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_dashboard_summary_default,
    list_periodic_services_default,
    list_occurrences_default,
    list_environmental_licenses_default,
    list_suppliers_default,
    list_epi_deliveries_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
