// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-periodic-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function textResult(data) {
  return { content: [{ type: "text", text: JSON.stringify(data) }] };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
async function planGate(ctx) {
  if (!ctx.isAuthenticated()) return errorResult("Not authenticated");
  const { data, error } = await supabaseForUser(ctx).rpc("get_company_access_status");
  const obj = data;
  if (error || !obj || obj.error) return errorResult("Could not verify the company plan.");
  if (obj.status === "expired") return errorResult("The company plan is expired. Renew it to use the API.");
  if (obj.plan !== "enterprise" && obj.status !== "trial") {
    return errorResult("Agent/API (MCP) access is available on the Enterprise plan only.");
  }
  return null;
}

// src/lib/mcp/tools/list-periodic-services.ts
var list_periodic_services_default = defineTool({
  name: "list_periodic_services",
  title: "List periodic services",
  description: "List HSE periodic services for the signed-in user's company (name, category, next due date, status).",
  inputSchema: {
    status: z.enum(["ok", "warning", "expired", "all"]).optional().describe("Filter by compliance status."),
    limit: z.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    const denied = await planGate(ctx);
    if (denied) return denied;
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("periodic_services").select("id,name,category_id,next_due_date,status,is_active").order("next_due_date", { ascending: true }).limit(limit);
    if (status && status !== "all") query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult(data);
  }
});

// src/lib/mcp/tools/list-occurrences.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_occurrences_default = defineTool2({
  name: "list_occurrences",
  title: "List incidents (IC & NC)",
  description: "List safety incidents and non-conformities for the signed-in user's company.",
  inputSchema: {
    type: z2.string().optional().describe("Filter by occurrence type (e.g. 'incident', 'non_conformity')."),
    limit: z2.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, limit }, ctx) => {
    const denied = await planGate(ctx);
    if (denied) return denied;
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("occurrences").select("id,description,type,severity,status,occurred_at,lost_days,location").order("occurred_at", { ascending: false }).limit(limit);
    if (type) query = query.eq("type", type);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return textResult(data);
  }
});

// src/lib/mcp/tools/list-environmental-licenses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_environmental_licenses_default = defineTool3({
  name: "list_environmental_licenses",
  title: "List environmental licenses",
  description: "List environmental licenses (expiring, valid, expired) for the signed-in user's company.",
  inputSchema: { limit: z3.number().int().min(1).max(200).default(50) },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const denied = await planGate(ctx);
    if (denied) return denied;
    const { data, error } = await supabaseForUser(ctx).from("environmental_licenses").select("id,license_number,issuing_body,issued_at,expires_at,status").order("expires_at", { ascending: true }).limit(limit);
    if (error) return errorResult(error.message);
    return textResult(data);
  }
});

// src/lib/mcp/tools/list-suppliers.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_suppliers_default = defineTool4({
  name: "list_suppliers",
  title: "List suppliers",
  description: "List suppliers registered by the signed-in user's company.",
  inputSchema: {
    search: z4.string().optional().describe("Substring match on supplier name."),
    limit: z4.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    const denied = await planGate(ctx);
    if (denied) return denied;
    let q = supabaseForUser(ctx).from("suppliers_safe").select("*").order("name", { ascending: true }).limit(limit);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult(data);
  }
});

// src/lib/mcp/tools/list-epi-deliveries.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_epi_deliveries_default = defineTool5({
  name: "list_epi_deliveries",
  title: "List EPI deliveries",
  description: "List recent PPE (EPI) deliveries with employee, item and quantity.",
  inputSchema: { limit: z5.number().int().min(1).max(200).default(50) },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const denied = await planGate(ctx);
    if (denied) return denied;
    const { data, error } = await supabaseForUser(ctx).from("epi_deliveries").select("id,delivered_at,quantity,reason,employees(name),epi_types(name,unit)").order("delivered_at", { ascending: false }).limit(limit);
    if (error) return errorResult(error.message);
    return textResult(data);
  }
});

// src/lib/mcp/tools/get-dashboard-summary.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_dashboard_summary_default = defineTool6({
  name: "get_dashboard_summary",
  title: "HSE dashboard summary",
  description: "Summary counts of open incidents, expiring services, expiring licenses, and active suppliers for the signed-in user's company.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const denied = await planGate(ctx);
    if (denied) return denied;
    const sb = supabaseForUser(ctx);
    const [occ, srv, lic, sup] = await Promise.all([
      sb.from("occurrences").select("id", { count: "exact", head: true }).neq("status", "closed"),
      sb.from("periodic_services").select("id", { count: "exact", head: true }).in("status", ["warning", "expired"]).eq("is_active", true),
      sb.from("environmental_licenses").select("id", { count: "exact", head: true }).neq("status", "vigente"),
      sb.from("suppliers_safe").select("id", { count: "exact", head: true })
    ]);
    return textResult({
      open_incidents: occ.count ?? 0,
      services_needing_attention: srv.count ?? 0,
      licenses_needing_attention: lic.count ?? 0,
      suppliers_total: sup.count ?? 0
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "jspyzzrmonxvgicqakzv";
var mcp_default = defineMcp({
  name: "evita-hse-mcp",
  title: "Evita HSE",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in user's HSE data in Evita: periodic services, incidents (IC & NC), environmental licenses, suppliers, EPI deliveries, and a dashboard summary. All results are scoped to the user's company via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_dashboard_summary_default,
    list_periodic_services_default,
    list_occurrences_default,
    list_environmental_licenses_default,
    list_suppliers_default,
    list_epi_deliveries_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
